### PR TITLE
TOOL-16724 bcc: build fails when using "--parallel" on Delphix buildserver

### PR DESCRIPTION
**Pull request by prakashsurya**
I don't understand the root cause, but when doing the build in parallel (i.e. `make -j2`), it fails when running on the Delphix based buildserver. This change modifies the build, such that we always use `make -j1`; obviously this isn't ideal, but until we root cause a fix the underlying problem, this would at least allow us to build on the Delphix buildserver.

As one might expect, this does increase the time to build the package by about 2x; I don't think this is a big deal, since we don't actually build this package very often, and the total time to build is still "reasonable" (i.e. ~20 mins).

Lastly, we haven't synced our bcc codebase with upstream in quite a while, so we might inherit a fix for this parallel building issue when we do that sync. At that time, we could look at adding back the "--parallel" flag, to see if the build would succeed with the updated code.

### CODE REVIEW

**Review by sdimitro — APPROVED** [review]
I'm good with the change, just a couple of questions:
* Does this bleeding-edge build also fail in the normal bootstrap VM?
* What does the error message look like?

**Comment by prakashsurya** [comment]
> What does the error message look like?

See [here](http://ops.jenkins-psurya.dcol2.delphix.com/job/linux-pkg/job/6.0/job/stage/job/build-package/job/bcc/job/pre-push/10/console) for an example failure.

> Does this bleeding-edge build also fail in the normal bootstrap VM?

You mean, does https://github.com/delphix/bcc/pull/13 fail on the current build image? If so.. yea, we can see the failure in that PR's checks.. i.e. see [here](https://github.com/delphix/bcc/pull/13/checks?check_run_id=9371891701) and link directly to the build [here](http://selfservice.jenkins.delphix.com/job/linux-pkg/job/6.0/job/stage/job/build-package/job/bcc/job/pre-push/5/console).

**Comment by prakashsurya** [comment]
Also, since testing this change out (i.e. no `--parallel`), I was able to get 3 consecutive successful builds on the Delphix buildserver image.. without it, I got multiple failures, and only one successful build (see [here](http://ops.jenkins-psurya.dcol2.delphix.com/job/linux-pkg/job/6.0/job/stage/job/build-package/job/bcc/job/pre-push/8/)). The fact that I was able to get one successful build without this change, though, made me think maybe it had something parallel race issue.. which led me to try this out, and this seems to be working..

**Review by sebroy — APPROVED** [review]

**Comment by prakashsurya** [comment]
I'm going to close this, and not land it..

turns out, with help from Seb, the issue is a result of there being a swap device on the Delphix buildserver.. currently, linux-pkg will try to dynamically add swap using a file on the root filesystem.. I've disabled that, since using swap on ZFS doesn't quite work.. but, if I use a dedicated disk for swap, seperated from the ZFS root pool, bcc will build on the Delphix buildserver just fine (even with `--parallel`)..

so, I think the better way to fix this is to modify linux-pkg to properly add the swap device when running on the Delphix buildserver.. I'll look into this approach, instead.

**Pull request closed without merging**
